Repository apache/incubator-seata, pull requests merged in 2019-10, with the labels that each got.

#1726 optimize:formating log messages
  core/src/main/java/io/seata/core/rpc/ChannelManager.java
  core/src/main/java/io/seata/core/rpc/DefaultServerMessageListenerImpl.java
  core/src/main/java/io/seata/core/rpc/netty/NettyClientChannelManager.java
  core/src/main/java/io/seata/core/rpc/netty/RpcClientHandler.java
Labels: first-time contributor

#1656 feature: support spring cloud config
  all/pom.xml
  config/pom.xml
  config/seata-config-core/src/main/java/io/seata/config/ConfigType.java
  config/seata-config-spring-cloud/pom.xml
  config/seata-config-spring-cloud/src/main/java/io/seata/config/springcloud/EnableSeataSpringConfig.java
  config/seata-config-spring-cloud/src/main/java/io/seata/config/springcloud/SpringCloudConfiguration.java
  config/seata-config-spring-cloud/src/main/java/io/seata/config/springcloud/SpringCloudConfigurationProvider.java
  config/seata-config-spring-cloud/src/main/java/io/seata/config/springcloud/SpringContextProvider.java
  config/seata-config-spring-cloud/src/main/resources/META-INF/services/io.seata.config.ConfigurationProvider
Labels: first-time contributor

#1755 test: enhance test coverage of seata common
  common/src/test/java/io/seata/common/exception/StoreExceptionTest.java
  common/src/test/java/io/seata/common/thread/NamedThreadFactoryTest.java
  common/src/test/java/io/seata/common/thread/PositiveAtomicCounterTest.java
  common/src/test/java/io/seata/common/util/CollectionUtilsTest.java
Labels: first-time contributor

#1786 optimize: simplify code
  discovery/seata-discovery-eureka/src/main/java/io/seata/discovery/registry/eureka/EurekaRegistryServiceImpl.java
  discovery/seata-discovery-nacos/src/main/java/io/seata/discovery/registry/nacos/NacosRegistryServiceImpl.java
  discovery/seata-discovery-redis/src/main/java/io/seata/discovery/registry/redis/RedisRegistryServiceImpl.java
  discovery/seata-discovery-sofa/src/main/java/io/seata/discovery/registry/sofa/SofaRegistryServiceImpl.java
  discovery/seata-discovery-zk/src/main/java/io/seata/discovery/registry/zk/ZookeeperRegisterServiceImpl.java
  spring/src/main/java/io/seata/spring/tcc/TccActionInterceptor.java
Labels: first-time contributor

#1460 feature:gzip compressor
  all/pom.xml
  compressor/pom.xml
  compressor/seata-compressor-all/pom.xml
  compressor/seata-compressor-gzip/pom.xml
  compressor/seata-compressor-gzip/src/main/java/io/seata/compressor/gzip/GzipCompressor.java
  compressor/seata-compressor-gzip/src/main/java/io/seata/compressor/gzip/GzipUtil.java
  compressor/seata-compressor-gzip/src/main/resources/META-INF/services/io.seata.core.compressor.Compressor
  compressor/seata-compressor-gzip/src/test/java/io/seata/compressor/gzip/GzipCompressorTest.java
  compressor/seata-compressor-gzip/src/test/java/io/seata/compressor/gzip/GzipUtilTest.java
  core/src/main/java/io/seata/core/compressor/Compressor.java
  core/src/main/java/io/seata/core/compressor/CompressorFactory.java
  core/src/main/java/io/seata/core/compressor/CompressorType.java
  core/src/main/java/io/seata/core/protocol/ProtocolConstants.java
  core/src/main/java/io/seata/core/rpc/netty/v1/ProtocolV1Decoder.java
  core/src/main/java/io/seata/core/rpc/netty/v1/ProtocolV1Encoder.java
  pom.xml
  server/pom.xml
Labels: Do Not Merge

#1802 test:changing HashMap to LinkedHashMap for deterministic iterations
  common/src/test/java/io/seata/common/util/CollectionUtilsTest.java
Labels: first-time contributor

#1742 feature:add seata-spring-boot-starter
  codec/seata-codec-seata/src/test/resources/file.conf
  codec/seata-codec-seata/src/test/resources/registry.conf
  config/seata-config-core/src/main/java/io/seata/config/ConfigurationFactory.java
  config/seata-config-core/src/main/java/io/seata/config/ExtConfigurationProvider.java
  config/seata-config-core/src/main/resources/file.conf
  config/seata-config-core/src/main/resources/registry.conf
  pom.xml
  seata-spring-boot-starter/pom.xml
  seata-spring-boot-starter/src/main/java/io/seata/spring/boot/autoconfigure/SeataAutoConfiguration.java
  seata-spring-boot-starter/src/main/java/io/seata/spring/boot/autoconfigure/StarterConstants.java
  seata-spring-boot-starter/src/main/java/io/seata/spring/boot/autoconfigure/properties/SeataProperties.java
  seata-spring-boot-starter/src/main/java/io/seata/spring/boot/autoconfigure/properties/file/ClientProperties.java
  seata-spring-boot-starter/src/main/java/io/seata/spring/boot/autoconfigure/properties/file/LockProperties.java
  seata-spring-boot-starter/src/main/java/io/seata/spring/boot/autoconfigure/properties/file/ServiceProperties.java
  seata-spring-boot-starter/src/main/java/io/seata/spring/boot/autoconfigure/properties/file/ShutdownProperties.java
  seata-spring-boot-starter/src/main/java/io/seata/spring/boot/autoconfigure/properties/file/SpringProperties.java
  seata-spring-boot-starter/src/main/java/io/seata/spring/boot/autoconfigure/properties/file/SupportProperties.java
  seata-spring-boot-starter/src/main/java/io/seata/spring/boot/autoconfigure/properties/file/ThreadFactoryProperties.java
  seata-spring-boot-starter/src/main/java/io/seata/spring/boot/autoconfigure/properties/file/TransactionProperties.java
  seata-spring-boot-starter/src/main/java/io/seata/spring/boot/autoconfigure/properties/file/TransportProperties.java
  seata-spring-boot-starter/src/main/java/io/seata/spring/boot/autoconfigure/properties/registry/ConfigApolloProperties.java
  seata-spring-boot-starter/src/main/java/io/seata/spring/boot/autoconfigure/properties/registry/ConfigConsulProperties.java
  seata-spring-boot-starter/src/main/java/io/seata/spring/boot/autoconfigure/properties/registry/ConfigEtcd3Properties.java
  seata-spring-boot-starter/src/main/java/io/seata/spring/boot/autoconfigure/properties/registry/ConfigFileProperties.java
  seata-spring-boot-starter/src/main/java/io/seata/spring/boot/autoconfigure/properties/registry/ConfigNacosProperties.java
  seata-spring-boot-starter/src/main/java/io/seata/spring/boot/autoconfigure/properties/registry/ConfigProperties.java
  seata-spring-boot-starter/src/main/java/io/seata/spring/boot/autoconfigure/properties/registry/ConfigZooKeeperProperties.java
  seata-spring-boot-starter/src/main/java/io/seata/spring/boot/autoconfigure/properties/registry/RegistryConsulProperties.java
  seata-spring-boot-starter/src/main/java/io/seata/spring/boot/autoconfigure/properties/registry/RegistryEtcd3Properties.java
  seata-spring-boot-starter/src/main/java/io/seata/spring/boot/autoconfigure/properties/registry/RegistryEurekaProperties.java
  seata-spring-boot-starter/src/main/java/io/seata/spring/boot/autoconfigure/properties/registry/RegistryFileProperties.java
  seata-spring-boot-starter/src/main/java/io/seata/spring/boot/autoconfigure/properties/registry/RegistryNacosProperties.java
  seata-spring-boot-starter/src/main/java/io/seata/spring/boot/autoconfigure/properties/registry/RegistryProperties.java
  seata-spring-boot-starter/src/main/java/io/seata/spring/boot/autoconfigure/properties/registry/RegistryRedisProperties.java
  seata-spring-boot-starter/src/main/java/io/seata/spring/boot/autoconfigure/properties/registry/RegistrySofaProperties.java
  seata-spring-boot-starter/src/main/java/io/seata/spring/boot/autoconfigure/properties/registry/RegistryZooKeeperProperties.java
  seata-spring-boot-starter/src/main/java/io/seata/spring/boot/autoconfigure/provider/SpringBootConfigurationProvider.java
  seata-spring-boot-starter/src/main/java/io/seata/spring/boot/autoconfigure/util/SpringUtils.java
  seata-spring-boot-starter/src/main/java/io/seata/spring/boot/autoconfigure/util/StringFormatUtils.java
  seata-spring-boot-starter/src/main/resources/META-INF/services/io.seata.config.ExtConfigurationProvider
  seata-spring-boot-starter/src/main/resources/META-INF/spring.factories
  server/src/main/resources/file.conf
  test/src/test/resources/file.conf
Labels: kind/feature
