Repository apache/incubator-seata, pull requests merged in 2020-01, with the labels that each got.

#2038 refactor: simplify to make seata-common more readable
  common/src/main/java/io/seata/common/executor/Callback.java
  common/src/main/java/io/seata/common/executor/Initialize.java
  common/src/main/java/io/seata/common/loader/EnhancedServiceLoader.java
  common/src/main/java/io/seata/common/thread/RejectedPolicies.java
  common/src/main/java/io/seata/common/util/CollectionUtils.java
  common/src/main/java/io/seata/common/util/NetUtil.java
  common/src/main/java/io/seata/common/util/ReflectionUtil.java
  common/src/main/java/io/seata/common/util/StringUtils.java
  common/src/test/java/io/seata/common/thread/RejectedPoliciesTest.java
  common/src/test/java/io/seata/common/util/NetUtilTest.java
  common/src/test/java/io/seata/common/util/ReflectionUtilTest.java
Labels: first-time contributor

#2145 bugfix: Saga report branch status incorrect when service retried succeed
  saga/seata-saga-engine-store/src/main/java/io/seata/saga/engine/store/db/DbAndReportTcStateLogStore.java
Labels: area/Saga, kind/bug

#1746 feature: add http support
  all/pom.xml
  integration/http/pom.xml
  integration/http/src/main/java/io/seata/integration/http/AbstractHttpExecutor.java
  integration/http/src/main/java/io/seata/integration/http/DefaultHttpExecutor.java
  integration/http/src/main/java/io/seata/integration/http/HttpAutoConfiguration.java
  integration/http/src/main/java/io/seata/integration/http/HttpExecutor.java
  integration/http/src/main/java/io/seata/integration/http/HttpHandlerExceptionResolver.java
  integration/http/src/main/java/io/seata/integration/http/TransactionPropagationIntercepter.java
  integration/http/src/main/java/io/seata/integration/http/XidResource.java
  integration/http/src/main/resources/META-INF/spring.factories
  integration/http/src/test/java/io/seata/integration/http/HttpTest.java
  integration/http/src/test/java/io/seata/integration/http/IndexController.java
  pom.xml
Labels: first-time contributor, kind/feature

#2192 optimize: override eureka getHostName() return ipAddress
  discovery/seata-discovery-eureka/src/main/java/io/seata/discovery/registry/eureka/CustomEurekaInstanceConfig.java
Labels: first-time contributor

#2179 bugfix:fix type casting problem when using redis as registry
  script/client/conf/registry.conf
  script/client/spring/application.properties
  script/client/spring/application.yml
  seata-spring-boot-starter/src/main/java/io/seata/spring/boot/autoconfigure/properties/registry/RegistryRedisProperties.java
  seata-spring-boot-starter/src/test/java/io/seata/spring/boot/autoconfigure/RedisAutoInjectionTypeConvertTest.java
  seata-spring-boot-starter/src/test/resources/spring/redis_auto_injectio_test.xml
Labels: first-time contributor

#2175 bugfix: fix direct buffer OOM
  core/src/main/java/io/seata/core/rpc/netty/AbstractRpcRemotingServer.java
  core/src/main/java/io/seata/core/rpc/netty/NettyServerConfig.java
Labels: Do Not Merge
