Repository apache/incubator-seata, pull requests merged in 2020-04, with the labels that each got.

#2449 bugfix: fix can not get table structure when start
  server/src/main/java/io/seata/server/storage/db/store/LogStoreDataBaseDAO.java
Labels: bug

#2456 bugfix: fix encode request error
  serializer/seata-serializer-seata/src/main/java/io/seata/serializer/seata/protocol/AbstractResultMessageCodec.java
  server/src/main/java/io/seata/server/AbstractTCInboundHandler.java
  server/src/main/java/io/seata/server/coordinator/DefaultCoordinator.java
  server/src/main/java/io/seata/server/coordinator/DefaultCore.java
Labels: bug

#2495 bugfix: fix the NPE and reduce the request when lockkey is null
  rm-datasource/src/main/java/io/seata/rm/datasource/ConnectionProxy.java
  server/src/main/java/io/seata/server/lock/AbstractLockManager.java
  server/src/main/java/io/seata/server/storage/db/lock/DataBaseLocker.java
Labels: bug

#2490 bugfix: fix RpcContext.addResource when resource is null
  core/src/main/java/io/seata/core/rpc/RpcContext.java
  core/src/test/java/io/seata/core/rpc/RpcContextTest.java
Labels: first-time contributor

#2419 bugfix: fix http testcase run failed
  integration/http/src/test/java/io/seata/integration/http/HttpTest.java
  integration/http/src/test/java/io/seata/integration/http/MockController.java
  integration/http/src/test/java/io/seata/integration/http/MockHttpExecuter.java
  integration/http/src/test/java/io/seata/integration/http/MockHttpServletRequest.java
  integration/http/src/test/java/io/seata/integration/http/MockRequest.java
  integration/http/src/test/java/io/seata/integration/http/MockResponse.java
  integration/http/src/test/java/io/seata/integration/http/MockWebServer.java
  integration/http/src/test/java/io/seata/integration/http/ServletMapping.java
Labels: bug

#2381 feature: support XA transaction mode
  bom/pom.xml
  core/src/main/java/io/seata/core/model/BranchType.java
  distribution/pom.xml
  rm-datasource/pom.xml
  rm-datasource/src/main/java/io/seata/rm/BaseDataSourceResource.java
  rm-datasource/src/main/java/io/seata/rm/RMHandlerXA.java
  rm-datasource/src/main/java/io/seata/rm/datasource/AbstractDataSourceCacheResourceManager.java
  rm-datasource/src/main/java/io/seata/rm/datasource/util/JdbcUtils.java
  rm-datasource/src/main/java/io/seata/rm/datasource/util/XAUtils.java
  rm-datasource/src/main/java/io/seata/rm/datasource/xa/AbstractConnectionProxyXA.java
  rm-datasource/src/main/java/io/seata/rm/datasource/xa/AbstractDataSourceProxyXA.java
  rm-datasource/src/main/java/io/seata/rm/datasource/xa/ConnectionProxyXA.java
  rm-datasource/src/main/java/io/seata/rm/datasource/xa/DataSourceProxyXA.java
  rm-datasource/src/main/java/io/seata/rm/datasource/xa/DataSourceProxyXANative.java
  rm-datasource/src/main/java/io/seata/rm/datasource/xa/ExecuteTemplateXA.java
  rm-datasource/src/main/java/io/seata/rm/datasource/xa/Holdable.java
  rm-datasource/src/main/java/io/seata/rm/datasource/xa/Holder.java
  rm-datasource/src/main/java/io/seata/rm/datasource/xa/PreparedStatementProxyXA.java
  rm-datasource/src/main/java/io/seata/rm/datasource/xa/ResourceManagerXA.java
  rm-datasource/src/main/java/io/seata/rm/datasource/xa/StatementProxyXA.java
  rm-datasource/src/main/java/io/seata/rm/datasource/xa/XABranchXid.java
  rm-datasource/src/main/java/io/seata/rm/datasource/xa/XAXid.java
  rm-datasource/src/main/java/io/seata/rm/datasource/xa/XAXidBuilder.java
  rm-datasource/src/main/resources/META-INF/services/io.seata.core.model.ResourceManager
  rm-datasource/src/main/resources/META-INF/services/io.seata.rm.AbstractRMHandler
  rm-datasource/src/test/java/io/seata/rm/xa/ConnectionProxyXATest.java
  rm-datasource/src/test/java/io/seata/rm/xa/DataSourceProxyXANativeTest.java
  rm-datasource/src/test/java/io/seata/rm/xa/DataSourceProxyXATest.java
  rm-datasource/src/test/java/io/seata/rm/xa/XAXidBuilderTest.java
  rm/src/main/java/io/seata/rm/AbstractRMHandler.java
  server/src/main/java/io/seata/server/session/GlobalSession.java
  server/src/main/java/io/seata/server/transaction/xa/XACore.java
  server/src/main/resources/META-INF/services/io.seata.server.coordinator.AbstractCore
  test/pom.xml
  test/src/test/java/io/seata/xa/XAModeTest2.java
Labels: kind/feature

#2529 bugfix: druid parameter optimization.
  server/src/main/java/io/seata/server/store/DruidDataSourceGenerator.java
Labels: first-time contributor

#2489 optimize: optimize exceptionHandler code logic
  core/src/main/java/io/seata/core/exception/AbstractExceptionHandler.java
Labels: first-time contributor

#2473 bugfix: flush condition of disk in file mode
  server/src/main/java/io/seata/server/session/SessionHolder.java
  server/src/main/java/io/seata/server/storage/file/store/FileTransactionStoreManager.java
Labels: bug

#2494 optimize: add methods to reduce redundant code
  tcc/src/main/java/io/seata/rm/tcc/interceptor/ActionContextUtil.java
Labels: first-time contributor

#2464 optimize: saga transaction editor enhancements
  saga/seata-saga-statemachine-designer/ggeditor/components/Page/index.js
  saga/seata-saga-statemachine-designer/src/Flow/WorkSpace.js
  saga/seata-saga-statemachine-designer/src/components/EditorItemPanel/FlowItemPanel.js
Labels: first-time contributor

#2455 bugfix: child module can't execute copyright and checkstyle inspection
  .travis.yml
  pom.xml
Labels: bug

#2308 feature:Saga add switch to control whether to register branch
  common/src/main/java/io/seata/common/Constants.java
  core/src/main/java/io/seata/core/constants/ConfigurationKeys.java
  core/src/main/java/io/seata/core/constants/DefaultValues.java
  saga/seata-saga-engine-store/src/main/java/io/seata/saga/engine/config/DbStateMachineConfig.java
  saga/seata-saga-engine-store/src/main/java/io/seata/saga/engine/store/db/DbAndReportTcStateLogStore.java
  saga/seata-saga-engine/src/main/java/io/seata/saga/engine/impl/ProcessCtrlStateMachineEngine.java
  script/client/conf/file.conf
  script/client/saga/db/db2.sql
  script/client/saga/db/h2.sql
  script/client/saga/db/mysql.sql
  script/client/saga/db/oracle.sql
  script/client/saga/db/postgresql.sql
  script/client/spring/application.properties
  script/client/spring/application.yml
  script/config-center/config.txt
  seata-spring-boot-starter/src/main/java/io/seata/spring/boot/autoconfigure/properties/file/RmProperties.java
  server/src/main/java/io/seata/server/session/GlobalSession.java
  test/src/test/java/io/seata/saga/engine/db/StateMachineDBTests.java
  test/src/test/resources/file.conf
  test/src/test/resources/saga/spring/statemachine_engine_db_test.xml
  test/src/test/resources/saga/sql/db2_init.sql
  test/src/test/resources/saga/sql/h2_init.sql
  test/src/test/resources/saga/sql/mysql_init.sql
  test/src/test/resources/saga/sql/oracle_init.sql
Labels: area/Saga, kind/feature

#2275 feature: support hsf on TCC transaction mode
  tcc/src/main/java/io/seata/rm/tcc/remoting/parser/HSFRemotingParser.java
  tcc/src/main/resources/META-INF/services/io.seata.rm.tcc.remoting.RemotingParser
Labels: first-time contributor

#2575 bugfix: fix executeBatch can not get targetSql in Statement mode
  rm-datasource/src/main/java/io/seata/rm/datasource/AbstractStatementProxy.java
  rm-datasource/src/main/java/io/seata/rm/datasource/StatementProxy.java
  rm-datasource/src/test/java/io/seata/rm/datasource/StatementProxyTest.java
Labels: bug, first-time contributor

#2543 bugfix: ApplicationKeeper ShutdownHook signal invalid.
  test/src/test/java/io/seata/common/ApplicationKeeper.java
Labels: first-time contributor

#2573 optimize: replace Random by ThreadLocalRandom in RandomLoadBalance
  discovery/seata-discovery-core/src/main/java/io/seata/discovery/loadbalance/RandomLoadBalance.java
Labels: first-time contributor

#2415 optimize: distinguish database behavior according to the branch type
  .travis.yml
  core/src/main/java/io/seata/core/context/RootContext.java
  core/src/test/java/io/seata/core/context/RootContextTest.java
  integration/dubbo-alibaba/src/main/java/io/seata/integration/dubbo/alibaba/AlibabaDubboTransactionPropagationFilter.java
  integration/dubbo/src/main/java/io/seata/integration/dubbo/ApacheDubboTransactionPropagationFilter.java
  rm-datasource/src/main/java/io/seata/rm/datasource/exec/ExecuteTemplate.java
  spring/src/main/java/io/seata/spring/tcc/TccActionInterceptor.java
  tm/src/test/java/io/seata/tm/api/APITest.java
Labels: Do Not Merge

#2618 bugfix: fix could not create folder in zookeeper
  discovery/seata-discovery-zk/src/main/java/io/seata/discovery/registry/zk/ZookeeperRegisterServiceImpl.java
Labels: first-time contributor
