Repository apache/incubator-seata, pull requests merged in 2023-12, with the labels that each got.

#6098 optimize: optimize the retry logic in the acquireMetadata method
  changes/en-us/2.x.md
  changes/zh-cn/2.x.md
  discovery/seata-discovery-raft/src/main/java/io/seata/discovery/registry/raft/RaftRegistryServiceImpl.java
Labels: module/discovery, type: optimize

#6034 optimize: using namespace from command line when deployment with helm charts
  changes/en-us/2.x.md
  changes/zh-cn/2.x.md
  script/server/helm/seata-server/templates/deployment.yaml
  script/server/helm/seata-server/templates/service.yaml
  script/server/helm/seata-server/templates/tests/test-connection.yaml
  script/server/helm/seata-server/values.yaml
Labels: first-time contributor, module/script, type: optimize

#6125 test: unbind xid in TransactionTemplateTest
  changes/en-us/2.x.md
  changes/zh-cn/2.x.md
  tm/src/test/java/io/seata/tm/api/TransactionTemplateTest.java
Labels: TM, module/tm, type: test

#6121 bugfix: the branch transaction order error when rolling back
  changes/en-us/2.x.md
  changes/zh-cn/2.x.md
  dependencies/pom.xml
  server/src/main/java/io/seata/server/coordinator/DefaultCore.java
Labels: type: bug, module/server

#6116 optimize: remove lgtm.com badge
  README.md
  changes/en-us/2.x.md
  changes/zh-cn/2.x.md
Labels: type: optimize

#6145 security: upgrade jettison to 1.5.4
  changes/en-us/2.x.md
  changes/zh-cn/2.x.md
  dependencies/pom.xml
  discovery/seata-discovery-eureka/pom.xml
Labels: Security

#6151 optimize: add workflow for `MacOS` and `Windows`
  .github/workflows/build.yml
  .github/workflows/test-druid.yml
  .github/workflows/test-os.yml
  .github/workflows/test.yml
  all/pom.xml
  build/pom.xml
  changes/en-us/develop.md
  changes/zh-cn/develop.md
  console/pom.xml
  core/src/main/java/io/seata/core/rpc/netty/AbstractNettyRemotingClient.java
  core/src/main/java/io/seata/core/serializer/SerializerSecurityRegistry.java
  dependencies/pom.xml
  discovery/seata-discovery-core/src/main/java/io/seata/discovery/registry/FileRegistryServiceImpl.java
  pom.xml
  server/pom.xml
  server/src/test/java/io/seata/server/session/redis/RedisDistributedLockerTest.java
  spring/pom.xml
  test/src/test/java/io/seata/core/rpc/netty/TmNettyClientTest.java
  tm/src/test/java/io/seata/tm/api/TransactionTemplateTest.java
Labels: type: optimize

#6144 security: upgrade nacos client to 1.4.6
  changes/en-us/2.x.md
  changes/zh-cn/2.x.md
  dependencies/pom.xml
Labels: Security

#6163 Revert "optimize: the high CPU usage issue of the rpcMergeMessageSend thread (#6061)
  changes/en-us/2.x.md
  changes/zh-cn/2.x.md
  core/src/main/java/io/seata/core/rpc/netty/AbstractNettyRemoting.java
  core/src/main/java/io/seata/core/rpc/netty/AbstractNettyRemotingClient.java
Labels: revert

#6101 bugfix: in dubbo 3.x version, the consumer can't generate tcc proxy.
  changes/en-us/2.x.md
  changes/zh-cn/2.x.md
  core/src/main/java/io/seata/core/rpc/RemotingServer.java
  core/src/main/java/io/seata/core/rpc/netty/ChannelManager.java
  integration-tx-api/src/main/java/io/seata/integration/tx/api/util/DubboUtil.java
Labels: type: bug, module/core, module/server, module/intergration-tx-api

#6104 bugfix: in dubbo 3.x version, the consumer can't generate tcc proxy(develop branch).
  changes/en-us/develop.md
  changes/zh-cn/develop.md
  server/src/main/java/io/seata/server/coordinator/AbstractCore.java
  spring/src/main/java/io/seata/spring/annotation/GlobalTransactionScanner.java
Labels: type: bug, module/spring, module/tcc

#6147 security: upgrade kafka-clients to 3.6.1
  changes/en-us/2.x.md
  changes/zh-cn/2.x.md
  dependencies/pom.xml
  server/pom.xml
Labels: Security

#6164 optimize: redis registry push empty protection optimize
  changes/en-us/2.x.md
  changes/zh-cn/2.x.md
  dependencies/pom.xml
  discovery/seata-discovery-nacos/src/test/java/io/seata/discovery/registry/nacos/NacosRegistryServiceImplTest.java
  discovery/seata-discovery-redis/pom.xml
  discovery/seata-discovery-redis/src/main/java/io/seata/discovery/registry/redis/RedisRegistryServiceImpl.java
  discovery/seata-discovery-redis/src/test/java/io/seata/discovery/registry/redis/RedisRegisterServiceImplTest.java
Labels: module/discovery, type: optimize

#6174 optimize: add ASF basic config
  .asf.yaml
  changes/en-us/2.x.md
  changes/zh-cn/2.x.md
Labels: type: optimize

#6148 optimize: support Nacos ram role authentication
  changes/en-us/2.x.md
  changes/zh-cn/2.x.md
  config/seata-config-nacos/src/main/java/io/seata/config/nacos/NacosConfiguration.java
  discovery/seata-discovery-nacos/src/main/java/io/seata/discovery/registry/nacos/NacosRegistryServiceImpl.java
  script/client/conf/registry.conf
  script/client/spring/application.properties
  script/client/spring/application.yml
  seata-spring-autoconfigure/seata-spring-autoconfigure-core/src/main/java/io/seata/spring/boot/autoconfigure/properties/config/ConfigNacosProperties.java
  seata-spring-autoconfigure/seata-spring-autoconfigure-core/src/main/java/io/seata/spring/boot/autoconfigure/properties/registry/RegistryNacosProperties.java
  server/src/main/resources/application.example.yml
Labels: module/config, module/discovery, type: optimize

#6184 optimize: update NOTICE file
  NOTICE
  changes/en-us/2.x.md
  changes/zh-cn/2.x.md
Labels: type: optimize

#6182 bugfix: guava-32.0.0-jre.jar zip file is empty
  changes/en-us/2.x.md
  changes/zh-cn/2.x.md
  dependencies/pom.xml
Labels: type: bug, dependencies

#6186 optimize: update README.md(update mailing list and repository urls)
  README.md
  changes/en-us/2.x.md
  changes/zh-cn/2.x.md
Labels: type: optimize

#6166 optimize: nettyPoolKey creation and update logic
  changes/en-us/2.x.md
  changes/zh-cn/2.x.md
  core/src/main/java/io/seata/core/rpc/netty/NettyClientChannelManager.java
  core/src/main/java/io/seata/core/rpc/netty/NettyPoolKey.java
Labels: module/core, type: optimize

#6194 optimize: fix asf.yaml parse error
  .asf.yaml
  changes/en-us/2.x.md
  changes/zh-cn/2.x.md
Labels: type: optimize

#6196 bugfix: asf config file format error
  .asf.yaml
Labels: type: bug

#6200 optimize: cancel required_status_checks
  .asf.yaml
Labels: type: optimize

#6195 optimize: update the url in change log to apache/incubator-seata
  changes/en-us/2.x.md
  changes/zh-cn/2.x.md
Labels: type: optimize, changelog

#6201 optimize: restore required_status_checks keep removing the context check
  .asf.yaml
  changes/en-us/2.x.md
  changes/zh-cn/2.x.md
Labels: type: optimize

#6154 optimize: console log optimize for "kubectl logs -f"
  changes/en-us/2.x.md
  changes/zh-cn/2.x.md
  distribution/bin/seata-server.sh
  server/src/main/java/io/seata/server/spring/listener/ServerApplicationListener.java
  server/src/main/resources/logback/console-appender.xml
Labels: module/server, type: optimize

#6204 bugfix: fix the problem that The incorrect configuration needs to be fixed
  changes/en-us/2.x.md
  changes/zh-cn/2.x.md
  script/config-center/config.txt
  server/src/main/resources/application.example.yml
Labels: first-time contributor, module/server, module/script

#6218 optimize:remove Seata-Docker link
  README.md
  changes/en-us/2.x.md
  changes/zh-cn/2.x.md
Labels: type: optimize
